package com.example.englishpracticer;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class wordsDataBase {
    String []  words ;
    String [] solutions ;
    String wordsList ;
    String solutionsList;

    public wordsDataBase(){
        this.wordsList = "superstition\n" +
                "pretext\n" +
                "cardigan\n" +
                "discrepancy\n" +
                "chivalry\n" +
                "sanguine\n" +
                "widow\n" +
                "purse\n" +
                "dreadful\n" +
                "dime\n" +
                "pious\n" +
                "wretched\n" +
                "vogue\n" +
                "horizon\n" +
                "lurking\n" +
                "pines\n" +
                "liability\n" +
                "warranty\n" +
                "discrepancy\n" +
                "infidelity\n" +
                "unease\n" +
                "interpolating\n" +
                "plumbing\n" +
                "credentials\n" +
                "contraceptives\n" +
                "nevertheless\n" +
                "vestige\n" +
                "woven\n" +
                "wardrobe\n" +
                "inspection\n" +
                "hereby\n" +
                "bulge\n" +
                "bolt\n" +
                "domestic\n" +
                "tenement\n" +
                "mortal\n" +
                "bum\n" +
                "drought\n" +
                "fortunate\n" +
                "wholesome\n" +
                "ripe\n" +
                "conspicuous\n" +
                "lout\n" +
                "erratically\n" +
                "infidelity\n" +
                "inspect\n" +
                "initially\n" +
                "contempt\n" +
                "bollards\n" +
                "lout\n" +
                "eminent\n" +
                "prominent\n" +
                "bashful\n" +
                "bosom\n" +
                "scrutinized\n" +
                "opt\n" +
                "bum\n" +
                "annotation\n" +
                "menagerie\n" +
                "amid\n" +
                "fission\n" +
                "criticism\n" +
                "senior\n" +
                "insofar\n" +
                "spouse\n" +
                "centenarian\n" +
                "brunt\n" +
                "coyly\n" +
                "owning\n" +
                "obediently\n" +
                "cattle\n" +
                "vicinity\n" +
                "prompt\n" +
                "sustainable\n" +
                "goons\n" +
                "earnest\n" +
                "ample\n" +
                "initially\n" +
                "dame\n" +
                "stimulation\n" +
                "deportation\n" +
                "candid\n" +
                "stump\n" +
                "marbles\n" +
                "singlet\n" +
                "corpse\n" +
                "plunder\n" +
                "edicts\n" +
                "whim\n" +
                "hedge\n" +
                "diversity\n" +
                "centenarian\n" +
                "stimulus\n" +
                "expulsion\n" +
                "deportation\n" +
                "exile\n" +
                "utter\n" +
                "gnarly\n" +
                "lousy\n" +
                "portrait\n" +
                "sermon\n" +
                "deliberation\n" +
                "dime\n" +
                "meager\n" +
                "barge\n" +
                "stall\n" +
                "acres\n" +
                "tenants\n" +
                "apt\n" +
                "prejudices\n" +
                "comprehension\n" +
                "glimpse\n" +
                "lingering\n" +
                "tantrum\n" +
                "echo\n" +
                "halo\n" +
                "absence\n" +
                "wreckage\n" +
                "galloping\n" +
                "consent\n" +
                "reminiscing\n" +
                "abstraction\n" +
                "assembly\n" +
                "obesity\n" +
                "induction\n" +
                "persistence\n" +
                "flank\n" +
                "horizon\n" +
                "rear\n" +
                "discerning\n" +
                "discernig\n" +
                "reciprocal\n" +
                "posterity\n" +
                "deliberation\n" +
                "assumption\n" +
                "harassed\n" +
                "pedestrian\n" +
                "fraud\n" +
                "deception\n" +
                "debut\n" +
                "hock\n" +
                "demoted\n" +
                "acquaintance\n" +
                "fusion\n" +
                "subjugation\n" +
                "precession\n" +
                "treadmill\n" +
                "overwhelmed\n" +
                "hordes\n" +
                "dispute\n" +
                "aisle\n" +
                "domestic\n" +
                "assumption\n" +
                "inciting\n" +
                "concealed\n" +
                "abate\n" +
                "disruption\n" +
                "havoc\n" +
                "devastating\n" +
                "loot\n" +
                "annihilation\n" +
                "ivory\n" +
                "conjectures\n" +
                "persuaded\n" +
                "evaporated\n" +
                "barricaded\n" +
                "stealth\n" +
                "evasion\n" +
                "reference\n" +
                "outfit\n" +
                "abashed\n" +
                "harassed\n" +
                "elated\n" +
                "attrition\n" +
                "drape\n" +
                "relinquishing\n" +
                "waiver\n" +
                "nor\n" +
                "veteran\n" +
                "creeping\n" +
                "perspiration\n" +
                "nimble\n" +
                "affinity\n" +
                "disdain\n" +
                "wrath\n" +
                "rage\n" +
                "pardon\n" +
                "immunity\n" +
                "mole\n" +
                "anxiety\n" +
                "riddle\n" +
                "smirk\n" +
                "compassion\n" +
                "frail\n" +
                "Amorous\n" +
                "patronize\n" +
                "hefty\n" +
                "gravel\n" +
                "slot\n" +
                "solemn\n" +
                "imbue\n" +
                "incompetence\n" +
                "yarns\n" +
                "resilience\n" +
                "insolent\n" +
                "rehearse\n" +
                "essay\n" +
                "pale\n" +
                "secular\n" +
                "clay\n" +
                "elimination\n" +
                "vaccine\n" +
                "deafen\n" +
                "bathrobe\n" +
                "bathrobe\n" +
                "clemency\n" +
                "lacked\n" +
                "destitute\n" +
                "beads\n" +
                "diligence\n" +
                "clandestine\n" +
                "apprehensive\n" +
                "foyer\n" +
                "grudge\n" +
                "novice\n" +
                "peacocks\n" +
                "form\n" +
                "duped\n" +
                "rite\n" +
                "inheritance\n" +
                "inclination\n" +
                "despair\n" +
                "frenetic\n" +
                "chairman\n" +
                "chairman\n" +
                "integrity\n" +
                "despair\n" +
                "vocation\n" +
                "salvation\n" +
                "alleged\n" +
                "indignation\n" +
                "rural\n" +
                "bound\n" +
                "aching\n" +
                "hive\n" +
                "heretic\n" +
                "loaf\n" +
                "stove\n" +
                "insofar\n" +
                "heresy\n" +
                "clogs\n" +
                "placard\n" +
                "enunciate\n" +
                "galvanise\n" +
                "condemn\n" +
                "wade\n" +
                "mourn\n" +
                "loaf\n" +
                "bargain\n" +
                "abstain\n" +
                "grovel\n" +
                "comply\n" +
                "distinguish\n" +
                "brace\n" +
                "alternate\n" +
                "blush\n" +
                "convey\n" +
                "incriminate\n" +
                "blunt\n" +
                "soak\n" +
                "sap\n" +
                "pester\n" +
                "pry\n" +
                "warble\n" +
                "extinguish\n" +
                "impeccable\n" +
                "tinker\n" +
                "dislodge\n" +
                "detain\n" +
                "indulge\n" +
                "elaborate\n" +
                "scrutinise\n" +
                "stir\n" +
                "invigorate\n" +
                "dispatch\n" +
                "amuse\n" +
                "thrive\n" +
                "manipulate\n" +
                "mend\n" +
                "inspect\n" +
                "gawk\n" +
                "swallow\n" +
                "glide\n" +
                "devise\n" +
                "jeer\n" +
                "stumble\n" +
                "blossom\n" +
                "limp\n" +
                "imply\n" +
                "graze\n" +
                "deprive\n" +
                "retain\n" +
                "grasp\n" +
                "poke\n" +
                "revert\n" +
                "undermine\n" +
                "apprehend\n" +
                "defecate\n" +
                "slander\n" +
                "indistinct\n" +
                "bind\n" +
                "tame\n" +
                "articulate\n" +
                "flee\n" +
                "postpone\n" +
                "render\n" +
                "clarify\n" +
                "distinguish\n" +
                "emphasize\n" +
                "retrieve\n" +
                "deafen\n" +
                "forge\n" +
                "deceive\n" +
                "incriminate\n" +
                "succeed\n" +
                "mitigate\n" +
                "bounce\n" +
                "ponder\n" +
                "deter\n" +
                "lend\n" +
                "decimate\n" +
                "contemplate\n" +
                "overcome\n" +
                "deteriorate\n" +
                "faint\n" +
                "wrangle\n" +
                "renounce\n" +
                "damp\n" +
                "bolster\n" +
                "emulate\n" +
                "plow\n" +
                "purge\n" +
                "caresses\n" +
                "implement\n" +
                "jester\n" +
                "apparent\n" +
                "alleged\n" +
                "extinguish\n" +
                "mercilessly\n" +
                "mercilessly\n" +
                "sip\n" +
                "obliterate\n" +
                "exploit\n" +
                "endure\n" +
                "alternate\n" +
                "elicit\n" +
                "dislodge\n" +
                "seldom\n" +
                "compensate\n" +
                "unravel\n" +
                "elaborate\n" +
                "mediate\n" +
                "comply\n" +
                "rein\n" +
                "curb\n" +
                "graze\n" +
                "in vain\n" +
                "integrate\n" +
                "amuse\n" +
                "spill\n" +
                "rub\n" +
                "portray\n" +
                "mediate\n" +
                "loathe\n" +
                "sew\n" +
                "contribute\n" +
                "squandered\n" +
                "drawer\n" +
                "tendency\n" +
                "velocity\n" +
                "pantry\n" +
                "imbecile\n" +
                "lunatic\n" +
                "dignified\n" +
                "disgruntled\n" +
                "contraception\n" +
                "executive\n" +
                "invigorating\n" +
                "vague\n" +
                "strife\n" +
                "deceived\n" +
                "ragged\n" +
                "hurdle\n" +
                "enterprise\n" +
                "pursuit\n" +
                "terrace\n" +
                "downpour\n" +
                "frown\n" +
                "downpour\n" +
                "dispute\n" +
                "barrier\n" +
                "brooch\n" +
                "apparatus\n" +
                "orbit\n" +
                "aisle\n" +
                "eerie\n" +
                "avalanche\n" +
                "comprehensive\n" +
                "implication\n" +
                "county\n" +
                "lever\n" +
                "venue\n" +
                "petrified\n" +
                "attribute\n" +
                "pastries\n" +
                "foyer\n" +
                "impasse\n" +
                "bewilderment\n" +
                "muddled\n" +
                "assortment\n" +
                "bewildering\n" +
                "diversity\n" +
                "exaggerating\n" +
                "culminates\n" +
                "plague\n" +
                "tray\n" +
                "fumbling\n" +
                "indices\n" +
                "pyre\n" +
                "kindles\n" +
                "falters\n" +
                "clamped\n" +
                "intrinsic\n" +
                "upheaval\n" +
                "heritage\n" +
                "flogged\n" +
                "concept\n" +
                "elongated\n" +
                "neglected\n" +
                "vendor\n" +
                "fond\n" +
                "reckoned\n" +
                "revitalizing\n" +
                "stifling\n" +
                "barrier\n" +
                "inundate\n" +
                "redundant\n" +
                "merger\n" +
                "venture\n" +
                "extraction\n" +
                "slanted\n" +
                "caresses\n" +
                "flagellation\n" +
                "embittered\n" +
                "disgruntled\n" +
                "mumbles\n" +
                "tune\n" +
                "apparatus\n" +
                "estranged\n" +
                "contraceptives\n" +
                "contraception\n" +
                "gnarly\n" +
                "devotion\n" +
                "inciting\n" +
                "itinerary\n" +
                "adore\n" +
                "avalanche\n" +
                "dubious\n" +
                "explicit\n" +
                "enticing\n" +
                "luring\n" +
                "hardship\n" +
                "predicament\n" +
                "aggregate\n" +
                "squints\n" +
                "polarised\n" +
                "asylum\n" +
                "vexing\n" +
                "mortar\n" +
                "aloof\n" +
                "puny\n" +
                "porch\n" +
                "soaring\n" +
                "daunting\n" +
                "beacon\n" +
                "compelling\n" +
                "mortgage\n" +
                "omitting\n" +
                "funneled\n" +
                "funnel\n" +
                "raging\n" +
                "teases\n" +
                "dwindling\n" +
                "falters\n" +
                "defies\n" +
                "defy\n" +
                "fragrance\n" +
                "agitated\n" +
                "apparent\n" +
                "fidelity\n" +
                "esteemed\n" +
                "prophet\n" +
                "nostril\n" +
                "inferior\n" +
                "feminine\n" +
                "compelled\n" +
                "holdfast\n" +
                "fidelity\n" +
                "adjourned\n" +
                "roaming\n" +
                "recreation\n" +
                "fraudster\n" +
                "audacious\n" +
                "hermit\n" +
                "flung\n" +
                "swarm\n" +
                "snorted\n" +
                "surge\n" +
                "burden\n" +
                "exploitation\n" +
                "borne\n" +
                "malleable\n" +
                "cripple\n" +
                "enthusiastic\n" +
                "fugitives\n" +
                "stilettos\n" +
                "prevalent\n" +
                "tumble\n" +
                "unfolds\n" +
                "triumph\n" +
                "retaliation\n" +
                "retaliate\n" +
                "feminine\n" +
                "lanes\n" +
                "fiber\n" +
                "hamper\n" +
                "ambient\n" +
                "worshiped\n" +
                "fling\n" +
                "errands\n" +
                "brooch\n" +
                "apron\n" +
                "cutlery\n" +
                "peril\n" +
                "parlour\n" +
                "rag\n" +
                "branch\n" +
                "turmoil\n" +
                "verge\n" +
                "idle\n" +
                "attic\n" +
                "bail\n" +
                "haze\n" +
                "congregation\n" +
                "devious\n" +
                "delicate\n" +
                "labor\n" +
                "carriage\n" +
                "hitherto\n" +
                "testament\n" +
                "advocate\n" +
                "fatigue\n" +
                "profound\n" +
                "humility\n" +
                "branch\n" +
                "branches\n" +
                "obstinacy\n" +
                "heap\n" +
                "vigilant\n" +
                "moths\n" +
                "splendor\n" +
                "leisure\n" +
                "mosaic\n" +
                "verdict\n" +
                "thread\n" +
                "savagery\n" +
                "abrupt\n" +
                "facet\n" +
                "clerk\n" +
                "intruder\n" +
                "burglar\n" +
                "fugitives\n" +
                "tweezer\n" +
                "solvency\n" +
                "luring\n" +
                "temptation\n" +
                "plod\n" +
                "facial\n" +
                "streak\n" +
                "pinnacle\n" +
                "statue\n" +
                "fur\n" +
                "flea\n" +
                "deer\n" +
                "consumption\n" +
                "grief\n" +
                "edict\n" +
                "arid\n" +
                "stench\n" +
                "quote\n" +
                "anticipation\n" +
                "viper\n" +
                "sprung\n" +
                "consumption\n" +
                "wasp\n" +
                "rhythm\n" +
                "plank\n" +
                "gloom\n" +
                "sacred\n" +
                "predetermined\n" +
                "crutches\n" +
                "clogs\n" +
                "dour\n" +
                "nabob\n" +
                "dour\n" +
                "coherent\n" +
                "teapot\n" +
                "ape\n" +
                "cordon\n" +
                "lamented\n" +
                "urchin\n" +
                "ease\n" +
                "flour\n" +
                "wrinkles\n" +
                "wilted\n" +
                "wither\n" +
                "vaulting\n" +
                "enchantment\n" +
                "kinship\n" +
                "imminence\n" +
                "hovering\n" +
                "vacant\n" +
                "clue\n" +
                "shallow\n" +
                "corporal\n" +
                "tenderness\n" +
                "saliva\n" +
                "quiver\n" +
                "teeming\n" +
                "sovereignty\n" +
                "decay\n" +
                "hub\n" +
                "bridle\n" +
                "veil\n" +
                "slack\n" +
                "limp\n" +
                "roar\n" +
                "domination\n" +
                "stool\n" +
                "bowed\n" +
                "tranquil\n" +
                "vagrant\n" +
                "prosperity\n" +
                "scraps\n" +
                "slug\n" +
                "frail\n" +
                "fringe\n" +
                "astray\n" +
                "terrain\n" +
                "swathed\n" +
                "convoy\n" +
                "parasol\n" +
                "gradient\n" +
                "subsided\n" +
                "wages\n" +
                "integrity\n" +
                "drubbing\n" +
                "realm\n" +
                "attribute\n" +
                "slumber\n" +
                "syndrome\n" +
                "mound\n" +
                "surcharge\n" +
                "retaliation\n" +
                "endorse\n" +
                "stray\n" +
                "queue\n" +
                "budge\n" +
                "orchestra\n" +
                "realm\n" +
                "portrayal\n" +
                "trinkets\n" +
                "pendant\n" +
                "exhibits\n" +
                "seams\n" +
                "heyday\n" +
                "infernal\n" +
                "mishap\n" +
                "remedy\n" ;

        this.solutionsList = "אֱמוּנָה טְפֵלָה\n" +
                "אֲמַתלָה\n" +
                "אֲרִיג צֶמֶר\n" +
                "אִי הַתְאָמָה\n" +
                "אַבִּירוּת\n" +
                "אַדְמוֹנִי\n" +
                "אַלמָנָה\n" +
                "אַרְנָק\n" +
                "אָיוֹם\n" +
                "אגורה\n" +
                "אדוק\n" +
                "אוּמלָל\n" +
                "אופנה\n" +
                "אופק\n" +
                "אורב\n" +
                "אורנים\n" +
                "אחריות\n" +
                "אחריות\n" +
                "אי התאמה\n" +
                "אי נאֱמנות\n" +
                "אי נוחות\n" +
                "אינטרפולציה\n" +
                "אינסטלציה\n" +
                "אישורים\n" +
                "אמצעי מניעה\n" +
                "אף על פי כן\n" +
                "אפוד\n" +
                "ארוג\n" +
                "ארון בגדים\n" +
                "בְּדִיקָה\n" +
                "בְּזֹאת\n" +
                "בְּלִיטָה\n" +
                "בְּרִיחַ\n" +
                "בֵּיתִי\n" +
                "בֵּית דִירוֹת\n" +
                "בֶּן תְמוּתָה\n" +
                "בַּטלָן\n" +
                "בַּצוֹרֶת\n" +
                "בַּר מַזָל\n" +
                "בָּרִיא\n" +
                "בָּשֵׁל\n" +
                "בּוֹלֵט לָעַיִן\n" +
                "בּוּר\n" +
                "באופן לא יציב\n" +
                "בגידה\n" +
                "בדוק\n" +
                "בהתחלה\n" +
                "בוז\n" +
                "בולולים\n" +
                "בולט\n" +
                "בולט\n" +
                "בולט\n" +
                "בושה\n" +
                "בחיק\n" +
                "בחן\n" +
                "בחר\n" +
                "בטלן\n" +
                "ביאור\n" +
                "ביבר\n" +
                "בין\n" +
                "ביקוע\n" +
                "ביקורת\n" +
                "בכיר\n" +
                "במידה\n" +
                "בן זוג\n" +
                "בן מאה\n" +
                "בנטל\n" +
                "בעדינות\n" +
                "בעלות\n" +
                "בצייתנות\n" +
                "בקר\n" +
                "בקרבת\n" +
                "בקש\n" +
                "בר קיימא\n" +
                "בריונים\n" +
                "ברצינות\n" +
                "בשפע\n" +
                "בתחילה\n" +
                "גְבֶרֶת\n" +
                "גְרִיָה\n" +
                "גֵרוּשׁ\n" +
                "גָלוּי לֵב\n" +
                "גדם\n" +
                "גוּלוֹת\n" +
                "גוּפִיָה\n" +
                "גוּפָה\n" +
                "גזל\n" +
                "גזרות\n" +
                "גחמה\n" +
                "גידור\n" +
                "גיוון\n" +
                "גיל מאה\n" +
                "גירוי\n" +
                "גירוש\n" +
                "גירוש\n" +
                "גלות\n" +
                "גמורה\n" +
                "גנרלי\n" +
                "גרוע\n" +
                "דְיוֹקָן\n" +
                "דְרָשָׁה\n" +
                "דִיוּן\n" +
                "דַיִם\n" +
                "דַל\n" +
                "דוברה\n" +
                "דוכן\n" +
                "דונם\n" +
                "דיירים\n" +
                "דירה\n" +
                "דעות קדומות\n" +
                "הֲבָנָה\n" +
                "הֲצָצָה\n" +
                "הִתמַהמְהוּת\n" +
                "הִתפָּרְצוּת זַעַם\n" +
                "הֵד\n" +
                "הֵל\n" +
                "הֶעְדֵר\n" +
                "הֶרֶס\n" +
                "הַדהָרָה\n" +
                "הַסכָּמָה\n" +
                "הַעֲלָאַת זִכרוֹנוֹת\n" +
                "הַפשָׁטָה\n" +
                "הַרכָּבָה\n" +
                "הַשׁמָנָה\n" +
                "הַשׁרָאָה\n" +
                "הַתמָדָה\n" +
                "האגף\n" +
                "האופק\n" +
                "האחורי\n" +
                "הבחנה\n" +
                "הבחנה\n" +
                "הדדיות\n" +
                "הדורות הבאים\n" +
                "הדיון\n" +
                "ההנחה\n" +
                "הוטרד\n" +
                "הולכי רגל\n" +
                "הונאה\n" +
                "הונאה\n" +
                "הופעת בכורה\n" +
                "הוק\n" +
                "הורד\n" +
                "היכרות\n" +
                "היתוך\n" +
                "הכנעה\n" +
                "הכרח\n" +
                "הליכון\n" +
                "המום\n" +
                "המוני\n" +
                "המחלוקת\n" +
                "המעבר\n" +
                "המקומית\n" +
                "הנחה\n" +
                "הסתה\n" +
                "הסתיר\n" +
                "הפחת\n" +
                "הפרעה\n" +
                "הרס\n" +
                "הרסנית\n" +
                "השלל\n" +
                "השמדה\n" +
                "השנהב\n" +
                "השערות\n" +
                "השתכנע\n" +
                "התאדה\n" +
                "התבצר\n" +
                "התגנבות\n" +
                "התחמקות\n" +
                "התייחסות\n" +
                "התלבושת\n" +
                "התנכל\n" +
                "התנכלו\n" +
                "התרוממות רוח\n" +
                "התשה\n" +
                "וילון\n" +
                "ויתור\n" +
                "ויתור\n" +
                "ולא\n" +
                "ותיק\n" +
                "זְחִילָה\n" +
                "זֵעָה\n" +
                "זָרִיז\n" +
                "זיקה\n" +
                "זלזול\n" +
                "זעם\n" +
                "זעם\n" +
                "חֲנִינָה\n" +
                "חֲסִינוּת\n" +
                "חֲפַרפֶּרֶת\n" +
                "חֲרָדָה\n" +
                "חִידָה\n" +
                "חִיוּך מְעוּשֶׂה\n" +
                "חֶמלָה\n" +
                "חַלָשׁ\n" +
                "חַשׁקָנִי\n" +
                "חָסדָנוּת\n" +
                "חָסוֹן\n" +
                "חָצָץ\n" +
                "חָרִיץ\n" +
                "חגיגי\n" +
                "חדור\n" +
                "חוֹסֶר כִּשָׁרוֹן\n" +
                "חוטים\n" +
                "חוסן\n" +
                "חוצפן\n" +
                "חזרות\n" +
                "חיבור\n" +
                "חיוור\n" +
                "חילוני\n" +
                "חימר\n" +
                "חיסול\n" +
                "חיסון\n" +
                "חירש\n" +
                "חלוק אמבטיה\n" +
                "חלוק רחצה\n" +
                "חנינה\n" +
                "חסר\n" +
                "חסר כל\n" +
                "חרוזים\n" +
                "חריצות\n" +
                "חשאי\n" +
                "חשש\n" +
                "טְרַקלִין\n" +
                "טִינָה\n" +
                "טִירוֹן\n" +
                "טווסים\n" +
                "טופס\n" +
                "טפטף\n" +
                "טקס\n" +
                "יְרוּשָׁה\n" +
                "יֵצֶר\n" +
                "יאוש\n" +
                "יוֹצֵא מִכֵּלָיו\n" +
                "יו\"ר\n" +
                "יושב ראש\n" +
                "יושרה\n" +
                "ייאוש\n" +
                "ייעוד\n" +
                "ישועה\n" +
                "כִּביָכוֹל\n" +
                "כַּעַס\n" +
                "כַּפרִי\n" +
                "כָּרוּך\n" +
                "כּוֹאֵב\n" +
                "כוורת\n" +
                "כופר\n" +
                "כיכר\n" +
                "כיריים\n" +
                "ככל\n" +
                "כפירה\n" +
                "כפכפים\n" +
                "כרזה\n" +
                "לְבַטֵא\n" +
                "לְגַלוֵן\n" +
                "לְגַנוֹת\n" +
                "לְהִשְׁתַכְשֵׁך\n" +
                "לְהִתְאַבֵּל\n" +
                "לְהִתְבַּטֵל\n" +
                "לְהִתְמַקֵחַ\n" +
                "לְהִתְנַזֵר\n" +
                "לְהִתְרַפֵּס\n" +
                "לְהֵעָנוֹת\n" +
                "לְהַבחִין\n" +
                "לְהַדֵק\n" +
                "לְהַחלִיף\n" +
                "לְהַסמִיק\n" +
                "לְהַעֲבִיר\n" +
                "לְהַפְלִיל\n" +
                "לְהַקְהוֹת\n" +
                "לְהַשְׁרוֹת\n" +
                "לְהַתִישׁ\n" +
                "לְהָצִיק\n" +
                "לְחַטֵט\n" +
                "לְטַרלֵל\n" +
                "לְכַבּוֹת\n" +
                "לְלֹא דוֹפִי\n" +
                "לְנַסוֹת לְתַקֵן\n" +
                "לְנַשֵׁל\n" +
                "לְעַכֵּב\n" +
                "לְפַנֵק\n" +
                "לְפַרֵט\n" +
                "לְפַשׁפֵּשׁ\n" +
                "לְרַגֵשׁ\n" +
                "לְרַעֲנֵן\n" +
                "לְשַׁגֵר\n" +
                "לְשַׁעֲשֵׁעַ\n" +
                "לְשַׂגְשֵׂג\n" +
                "לְתַפְעֵל\n" +
                "לְתַקֵן\n" +
                "לִבדוֹק\n" +
                "לִבהוֹת\n" +
                "לִבלוֹעַ\n" +
                "לִדאוֹת\n" +
                "לִהַמצִיא\n" +
                "לִלְעוֹג\n" +
                "לִמְעוֹד\n" +
                "לִפְרוֹחַ\n" +
                "לִצְלוֹעַ\n" +
                "לִרְמוֹז\n" +
                "לִרְעוֹת\n" +
                "לִשְׁלוֹל\n" +
                "לִשְׁמוֹר\n" +
                "לִתְפּוֹס\n" +
                "לִתְקוֹעַ\n" +
                "לַחֲזוֹר\n" +
                "לַחתוֹר\n" +
                "לַעֲצוֹר\n" +
                "לַעֲשׂוֹת אֵת צְרָכָיו\n" +
                "לָשׁוֹן הָרַע\n" +
                "לֹא בָּרוּר\n" +
                "לאגד\n" +
                "לאלף\n" +
                "לבטא\n" +
                "לברוח\n" +
                "לדחות\n" +
                "לדקלם\n" +
                "להבהיר\n" +
                "להבחין\n" +
                "להדגיש\n" +
                "להחזיר\n" +
                "להחריש\n" +
                "להחשיל\n" +
                "להטעות\n" +
                "להפליל\n" +
                "להצליח\n" +
                "להקל\n" +
                "להקפיץ\n" +
                "להרהר\n" +
                "להרתיע\n" +
                "להשאיל\n" +
                "להשמיד\n" +
                "להתבונן\n" +
                "להתגבר\n" +
                "להתדרדר\n" +
                "להתעלף\n" +
                "להתקוטט\n" +
                "לוותר\n" +
                "לח\n" +
                "לחזק\n" +
                "לחקות\n" +
                "לחרוש\n" +
                "לטהר\n" +
                "ליטופים\n" +
                "ליישם\n" +
                "ליצן החצר\n" +
                "לכאורה\n" +
                "לכאורה\n" +
                "לכבות\n" +
                "ללא רחם\n" +
                "ללא רחמים\n" +
                "ללגום\n" +
                "למחוק\n" +
                "לנצל\n" +
                "לסבול\n" +
                "לסירוגין\n" +
                "לעורר\n" +
                "לעקור\n" +
                "לעתים רחוקות\n" +
                "לפצות\n" +
                "לפרום\n" +
                "לפרט\n" +
                "לפשר\n" +
                "לציית\n" +
                "לרסן\n" +
                "לרסן\n" +
                "לרעות\n" +
                "לשווא\n" +
                "לשלב\n" +
                "לשעשע\n" +
                "לשפוך\n" +
                "לשפשף\n" +
                "לתאר\n" +
                "לתווך\n" +
                "לתעב\n" +
                "לתפור\n" +
                "לתרום\n" +
                "מְבוּזבָּז\n" +
                "מְגֵרָה\n" +
                "מְגַמָה\n" +
                "מְהִירוּת\n" +
                "מְזָוֶה\n" +
                "מְטוּמטָם\n" +
                "מְטוּרָף\n" +
                "מְכוּבָּד\n" +
                "מְמוּרמָר\n" +
                "מְנִיעַת הֵרָיוֹן\n" +
                "מְנַהֵל\n" +
                "מְעוֹדֵד\n" +
                "מְעוּרפָּל\n" +
                "מְרִיבָה\n" +
                "מְרוּמֶה\n" +
                "מְרוּפָּט\n" +
                "מְשׂוֹכָה\n" +
                "מִפְעָל\n" +
                "מִרדָף\n" +
                "מִרפֶּסֶת\n" +
                "מִשׁפָּך\n" +
                "מַבָּט כּוֹעֵס\n" +
                "מַבּוּל\n" +
                "מַחֲלוֹקֶת\n" +
                "מַחסוֹם\n" +
                "מַכבֵּנָה\n" +
                "מַנגָנוֹן\n" +
                "מַסלוּל\n" +
                "מַעֲבָר\n" +
                "מַפְחִיד\n" +
                "מַפּוֹלֶת שְׁלָגִים\n" +
                "מַקִיף\n" +
                "מַשְׁמָעוּת\n" +
                "מָחוֹז\n" +
                "מָנוֹף\n" +
                "מָקוֹם מִפגָשׁ\n" +
                "מאובן\n" +
                "מאפיין\n" +
                "מאפים\n" +
                "מבואה\n" +
                "מבוי סתום\n" +
                "מבוכה\n" +
                "מבולבל\n" +
                "מבחר\n" +
                "מבלבל\n" +
                "מגוון\n" +
                "מגזים\n" +
                "מגיע לשיאו\n" +
                "מגיפה\n" +
                "מגש\n" +
                "מגשש\n" +
                "מדדים\n" +
                "מדורה\n" +
                "מדליק\n" +
                "מדשדש\n" +
                "מהודק\n" +
                "מהותי\n" +
                "מהפך\n" +
                "מוֹרֶשֶׁת\n" +
                "מוּכֶּה\n" +
                "מוּשָׂג\n" +
                "מוארך\n" +
                "מוזנח\n" +
                "מוכר\n" +
                "מחבב\n" +
                "מחושב\n" +
                "מחייה מחדש\n" +
                "מחניק\n" +
                "מחסום-מתרומם\n" +
                "מיותר\n" +
                "מיותר\n" +
                "מיזוג\n" +
                "מיזם\n" +
                "מיצוי\n" +
                "מלוכסנות\n" +
                "מלטף\n" +
                "מלקות\n" +
                "ממורמר\n" +
                "ממורמר\n" +
                "ממלמל\n" +
                "מנגינה\n" +
                "מנגנון\n" +
                "מנוכר\n" +
                "מניעה\n" +
                "מניעה\n" +
                "מסוקס\n" +
                "מסירות\n" +
                "מסית\n" +
                "מסלול נסיעה\n" +
                "מעריצה\n" +
                "מפולת\n" +
                "מפוקפק\n" +
                "מפורשות\n" +
                "מפתה\n" +
                "מפתה\n" +
                "מצוקה\n" +
                "מצוקה\n" +
                "מצטבר\n" +
                "מצמרר\n" +
                "מקוטב\n" +
                "מקלט\n" +
                "מרגיז\n" +
                "מרגמה\n" +
                "מרוחק\n" +
                "מרושע\n" +
                "מרפסת\n" +
                "מרקיע\n" +
                "מרתיע\n" +
                "משואה\n" +
                "משכנע\n" +
                "משכנתא\n" +
                "משמיט\n" +
                "משפך\n" +
                "משפך\n" +
                "משתוללת\n" +
                "מתגרה\n" +
                "מתדלדל\n" +
                "מתערער\n" +
                "מתריס\n" +
                "מתריס\n" +
                "נִיחוֹחַ\n" +
                "נִסעָר\n" +
                "נִרְאֶה\n" +
                "נֶאֱמָנוּת\n" +
                "נַעֲרָץ\n" +
                "נָבִיא\n" +
                "נָחִיר\n" +
                "נָחוּת\n" +
                "נָשִׁי\n" +
                "נאלץ\n" +
                "נאמנות\n" +
                "נאמנות\n" +
                "נדחה\n" +
                "נדידה\n" +
                "נוֹפֶשׁ\n" +
                "נוכל\n" +
                "נועז\n" +
                "נזיר\n" +
                "נזרק\n" +
                "נחיל\n" +
                "נחר\n" +
                "נחשול\n" +
                "נטל\n" +
                "ניצול של אדם או משאבים על מנת להרוויח מכך\n" +
                "נישא\n" +
                "ניתן לניפוח\n" +
                "נכה\n" +
                "נלהב\n" +
                "נמלטים\n" +
                "נעלי עקב\n" +
                "נפוצה\n" +
                "נפילה\n" +
                "נפרש\n" +
                "נצחון\n" +
                "נקמה\n" +
                "נקמה\n" +
                "נשית\n" +
                "נתיבים\n" +
                "סִיב\n" +
                "סַל\n" +
                "סביבה\n" +
                "סגדו\n" +
                "סטוץ\n" +
                "סידורים\n" +
                "סיכה\n" +
                "סינר\n" +
                "סכו\"ם\n" +
                "סכנה\n" +
                "סלון\n" +
                "סמרטוט\n" +
                "סניף\n" +
                "סערה\n" +
                "סף\n" +
                "סרק\n" +
                "עֲלִיַת גַג\n" +
                "עֲרֵבוּת\n" +
                "עֲרָפֶל\n" +
                "עֵדָה\n" +
                "עַרמוּמִי\n" +
                "עָדִין\n" +
                "עבודה\n" +
                "עגלה\n" +
                "עד כה\n" +
                "עדות\n" +
                "עוֹרֵך דִין\n" +
                "עייפות\n" +
                "עמוק\n" +
                "ענווה\n" +
                "ענף\n" +
                "ענפים\n" +
                "עקשנות\n" +
                "ערימה\n" +
                "ערנות\n" +
                "עש\n" +
                "פְּאֵר\n" +
                "פְּנַאִי\n" +
                "פְּסִיפָס\n" +
                "פְּסַק דִין\n" +
                "פְּתִיל\n" +
                "פִּראוּת\n" +
                "פִּתְאוֹמִי\n" +
                "פָּן\n" +
                "פָּקִיד\n" +
                "פּוֹלֵשׁ\n" +
                "פּוֹרֵץ\n" +
                "פושעים\n" +
                "פינצטה\n" +
                "פירעון\n" +
                "פיתוי\n" +
                "פיתוי\n" +
                "פלוד\n" +
                "פנים\n" +
                "פס\n" +
                "פסגה\n" +
                "פסל\n" +
                "פרווה\n" +
                "פרעוש\n" +
                "צְבִי\n" +
                "צְרִיכָה\n" +
                "צַעַר\n" +
                "צו\n" +
                "צחיח\n" +
                "צחנה\n" +
                "ציטוט\n" +
                "ציפייה\n" +
                "צפע\n" +
                "צצו\n" +
                "צריכת\n" +
                "צרעה\n" +
                "קֶצֶב\n" +
                "קֶרֶשׁ\n" +
                "קַדרוּת\n" +
                "קָדוֹשׁ\n" +
                "קבועה מראש\n" +
                "קביים\n" +
                "קבקבים\n" +
                "קוֹדֵר\n" +
                "קוֹרַח\n" +
                "קודר\n" +
                "קוהרנטי\n" +
                "קומקום\n" +
                "קוף\n" +
                "קורדון\n" +
                "קינן\n" +
                "קיפודי\n" +
                "קלות\n" +
                "קמח\n" +
                "קמטים\n" +
                "קמל\n" +
                "קמל\n" +
                "קמרון\n" +
                "קסם\n" +
                "קרבה\n" +
                "קרבה\n" +
                "רְחִיפָה\n" +
                "רֵיק\n" +
                "רֶמֶז\n" +
                "רָדוּד\n" +
                "רב\"ט\n" +
                "רוֹך\n" +
                "רוֹק\n" +
                "רועד\n" +
                "רועמת\n" +
                "ריבונות\n" +
                "ריקבון\n" +
                "רכזת\n" +
                "רסן\n" +
                "רעלה\n" +
                "רפוי\n" +
                "רפוי\n" +
                "שְׁאָגָה\n" +
                "שְׁלִיטָה\n" +
                "שְׁרַפרַף\n" +
                "שָׁחוּחַ\n" +
                "שָׁקֶט\n" +
                "שׁוֹטֵט\n" +
                "שִׂגשׂוּג\n" +
                "שאריות\n" +
                "שבלול\n" +
                "שברירי\n" +
                "שוליים\n" +
                "שולל\n" +
                "שטח\n" +
                "שטף\n" +
                "שיירה\n" +
                "שימשיה\n" +
                "שיפוע\n" +
                "שככה\n" +
                "שכר\n" +
                "שלמות\n" +
                "תְבוּסָה\n" +
                "תְחוּם\n" +
                "תְכוּנָה\n" +
                "תְנוּמָה\n" +
                "תִסמוֹנֶת\n" +
                "תֵל\n" +
                "תַשׁלוּם נוֹסָף\n" +
                "תגמול\n" +
                "תומכים\n" +
                "תועה\n" +
                "תור\n" +
                "תזוז\n" +
                "תזמורת\n" +
                "תחום\n" +
                "תיאור\n" +
                "תכשיטים\n" +
                "תליון\n" +
                "תערוכות\n" +
                "תפרים\n" +
                "תקופת הזוהר\n" +
                "תקיף\n" +
                "תקלה\n" +
                "תרופה\n" ;

        words = wordsList.split("\n");
        solutions = solutionsList.split("\n");


    }
    public String[] getWord(){
        double x = (Math.random()) * words.length-1;
        int y = (int) x;
        String[] output = new String [2];
        output[0] = words[y];
        output[1] = solutions [y];

        return output;
    }

    public static void main(String[] args) {
        System.out.println("123");
    }

}